# Site settings
url: http://precision-tech-llc.com
baseurl: ""
title: Precision Tech LLC
email: mgazzara@precision-tech-llc.com
description: "Precision Tech is a fabrication machine shop in Hammonton, New Jersey. We also have certified welders, providing welding services for all metals"

# Google Analytics ID
google_analytics_id: UA-72318604-1

# Postal address (add as many lines as necessary)
address:
  - line: 931 8th Street
  - line: Hammonton, NJ 08037

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff8c00
  secondary: ffad33
  secondary-dark: 333
  services-icons: d9d9d9

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: facebook
#    url: #
  - title: github
    url: http://github.com/precision-tech

# Build settings
markdown: kramdown
permalink: pretty
