url: http://precision-tech-llc.com
baseurl: ""

# Site settings
title: Precision Tech LLC
email: mgazzara@precision-tech-llc.com
description: "Fabrication machine shop services hammonton nj new jersey all metals welding"
google_analytics_id: UA-72318604-1

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-old: fed136
  primary: ff9900
  secondary-old: fec503
  secondary: ffad33
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 931 8th Street
  - line: Hammonton, NJ 08037

# Build settings
markdown: kramdown
permalink: pretty
